export const Roles = {
  TH: "TH",
  GTH: "GTH",
  OPERACIONES: "OPERACIONES",
  DIRECTORIO: "DIRECTORIO",
  LIDER: "LIDER",
  FUNCIONARIO_FABRICA: "FUNCIONARIO_FABRICA",
  FUNCIONARIO_TERCERIZADO: "FUNCIONARIO_TERCERIZADO",
  ADMINISTRADOR_DEL_SISTEMA: "ADMINISTRADOR_DEL_SISTEMA",
  TALENTO_HUMANO: "TALENTO_HUMANO",
} as const;

export type Roles = typeof Roles[keyof typeof Roles];
